name: unittest
on:
  push:
    paths:
      - 'uv.lock'
      - 'pyproject.toml'
      - 'pytdscf/**'
      - 'tests/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: uv-install
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: install-mpi
      run: sudo apt update && sudo apt install libopenmpi-dev
    - name: pytdscf-dev-install
      run: uv sync --extra mpi
    - name: pytest
      continue-on-error: true
      id: pytest
      run: uv run pytest
    - name: pytest-mpi
      continue-on-error: true
      id: pytest-mpi
      run: mpiexec -n 2 uv run pytest tests/test_mpi*.py
    - name: pytest rerun failed
      if: ${{ steps.pytest.outcome == 'failure'}}
      run: uv run pytest --lf --showlocals --tb=long --log-level=DEBUG
    - name: pytest-mpi rerun failed
      if: ${{ steps.pytest-mpi.outcome == 'failure'}}
      run: mpiexec -n 2 uv run pytest tests/test_mpi*.py --lf --showlocals --tb=long --log-level=DEBUG
